name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - develop
trigger:
  branches:
    include:
      - develop

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-thankful-tree-047ab5e10-variable-group
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
  - checkout: self
    submodules: true
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install --force'
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_TREE_047AB5E10)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding St.atic Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "dist/mantenimiento" # Built app content directory - optional
###### End of Repository/Build Configurations ######

